version: '1.0'

services:
  front:
    image: front
    ports:
      - 8888:8888
    expose:
      - 8888

  front2:
    image: front2
    ports:
      - 8081:8081
    expose:
      - 8081

  back:
    image: node_workshop
    ports:
      - 3000:3000
    restart:
      on-failure